// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: can_message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_can_5fmessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_can_5fmessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_can_5fmessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_can_5fmessage_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_can_5fmessage_2eproto;
namespace canproto {
class CanFrame;
struct CanFrameDefaultTypeInternal;
extern CanFrameDefaultTypeInternal _CanFrame_default_instance_;
class Signal;
struct SignalDefaultTypeInternal;
extern SignalDefaultTypeInternal _Signal_default_instance_;
}  // namespace canproto
PROTOBUF_NAMESPACE_OPEN
template<> ::canproto::CanFrame* Arena::CreateMaybeMessage<::canproto::CanFrame>(Arena*);
template<> ::canproto::Signal* Arena::CreateMaybeMessage<::canproto::Signal>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace canproto {

// ===================================================================

class Signal final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:canproto.Signal) */ {
 public:
  inline Signal() : Signal(nullptr) {}
  ~Signal() override;
  explicit PROTOBUF_CONSTEXPR Signal(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Signal(const Signal& from);
  Signal(Signal&& from) noexcept
    : Signal() {
    *this = ::std::move(from);
  }

  inline Signal& operator=(const Signal& from) {
    CopyFrom(from);
    return *this;
  }
  inline Signal& operator=(Signal&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Signal& default_instance() {
    return *internal_default_instance();
  }
  static inline const Signal* internal_default_instance() {
    return reinterpret_cast<const Signal*>(
               &_Signal_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Signal& a, Signal& b) {
    a.Swap(&b);
  }
  inline void Swap(Signal* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Signal* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Signal* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Signal>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Signal& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Signal& from) {
    Signal::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Signal* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "canproto.Signal";
  }
  protected:
  explicit Signal(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kUnitFieldNumber = 3,
    kPhysicalValueFieldNumber = 2,
    kRawValueFieldNumber = 4,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string unit = 3;
  void clear_unit();
  const std::string& unit() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_unit(ArgT0&& arg0, ArgT... args);
  std::string* mutable_unit();
  PROTOBUF_NODISCARD std::string* release_unit();
  void set_allocated_unit(std::string* unit);
  private:
  const std::string& _internal_unit() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_unit(const std::string& value);
  std::string* _internal_mutable_unit();
  public:

  // double physical_value = 2;
  void clear_physical_value();
  double physical_value() const;
  void set_physical_value(double value);
  private:
  double _internal_physical_value() const;
  void _internal_set_physical_value(double value);
  public:

  // int64 raw_value = 4;
  void clear_raw_value();
  int64_t raw_value() const;
  void set_raw_value(int64_t value);
  private:
  int64_t _internal_raw_value() const;
  void _internal_set_raw_value(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:canproto.Signal)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr unit_;
    double physical_value_;
    int64_t raw_value_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_can_5fmessage_2eproto;
};
// -------------------------------------------------------------------

class CanFrame final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:canproto.CanFrame) */ {
 public:
  inline CanFrame() : CanFrame(nullptr) {}
  ~CanFrame() override;
  explicit PROTOBUF_CONSTEXPR CanFrame(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CanFrame(const CanFrame& from);
  CanFrame(CanFrame&& from) noexcept
    : CanFrame() {
    *this = ::std::move(from);
  }

  inline CanFrame& operator=(const CanFrame& from) {
    CopyFrom(from);
    return *this;
  }
  inline CanFrame& operator=(CanFrame&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CanFrame& default_instance() {
    return *internal_default_instance();
  }
  static inline const CanFrame* internal_default_instance() {
    return reinterpret_cast<const CanFrame*>(
               &_CanFrame_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(CanFrame& a, CanFrame& b) {
    a.Swap(&b);
  }
  inline void Swap(CanFrame* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CanFrame* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CanFrame* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CanFrame>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CanFrame& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CanFrame& from) {
    CanFrame::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CanFrame* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "canproto.CanFrame";
  }
  protected:
  explicit CanFrame(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSignalListFieldNumber = 3,
    kMessageNameFieldNumber = 2,
    kMessageIdFieldNumber = 1,
  };
  // repeated .canproto.Signal signal_list = 3;
  int signal_list_size() const;
  private:
  int _internal_signal_list_size() const;
  public:
  void clear_signal_list();
  ::canproto::Signal* mutable_signal_list(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::canproto::Signal >*
      mutable_signal_list();
  private:
  const ::canproto::Signal& _internal_signal_list(int index) const;
  ::canproto::Signal* _internal_add_signal_list();
  public:
  const ::canproto::Signal& signal_list(int index) const;
  ::canproto::Signal* add_signal_list();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::canproto::Signal >&
      signal_list() const;

  // string message_name = 2;
  void clear_message_name();
  const std::string& message_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message_name();
  PROTOBUF_NODISCARD std::string* release_message_name();
  void set_allocated_message_name(std::string* message_name);
  private:
  const std::string& _internal_message_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message_name(const std::string& value);
  std::string* _internal_mutable_message_name();
  public:

  // uint32 message_id = 1;
  void clear_message_id();
  uint32_t message_id() const;
  void set_message_id(uint32_t value);
  private:
  uint32_t _internal_message_id() const;
  void _internal_set_message_id(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:canproto.CanFrame)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::canproto::Signal > signal_list_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_name_;
    uint32_t message_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_can_5fmessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Signal

// string name = 1;
inline void Signal::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& Signal::name() const {
  // @@protoc_insertion_point(field_get:canproto.Signal.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Signal::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:canproto.Signal.name)
}
inline std::string* Signal::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:canproto.Signal.name)
  return _s;
}
inline const std::string& Signal::_internal_name() const {
  return _impl_.name_.Get();
}
inline void Signal::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* Signal::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* Signal::release_name() {
  // @@protoc_insertion_point(field_release:canproto.Signal.name)
  return _impl_.name_.Release();
}
inline void Signal::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:canproto.Signal.name)
}

// double physical_value = 2;
inline void Signal::clear_physical_value() {
  _impl_.physical_value_ = 0;
}
inline double Signal::_internal_physical_value() const {
  return _impl_.physical_value_;
}
inline double Signal::physical_value() const {
  // @@protoc_insertion_point(field_get:canproto.Signal.physical_value)
  return _internal_physical_value();
}
inline void Signal::_internal_set_physical_value(double value) {
  
  _impl_.physical_value_ = value;
}
inline void Signal::set_physical_value(double value) {
  _internal_set_physical_value(value);
  // @@protoc_insertion_point(field_set:canproto.Signal.physical_value)
}

// string unit = 3;
inline void Signal::clear_unit() {
  _impl_.unit_.ClearToEmpty();
}
inline const std::string& Signal::unit() const {
  // @@protoc_insertion_point(field_get:canproto.Signal.unit)
  return _internal_unit();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Signal::set_unit(ArgT0&& arg0, ArgT... args) {
 
 _impl_.unit_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:canproto.Signal.unit)
}
inline std::string* Signal::mutable_unit() {
  std::string* _s = _internal_mutable_unit();
  // @@protoc_insertion_point(field_mutable:canproto.Signal.unit)
  return _s;
}
inline const std::string& Signal::_internal_unit() const {
  return _impl_.unit_.Get();
}
inline void Signal::_internal_set_unit(const std::string& value) {
  
  _impl_.unit_.Set(value, GetArenaForAllocation());
}
inline std::string* Signal::_internal_mutable_unit() {
  
  return _impl_.unit_.Mutable(GetArenaForAllocation());
}
inline std::string* Signal::release_unit() {
  // @@protoc_insertion_point(field_release:canproto.Signal.unit)
  return _impl_.unit_.Release();
}
inline void Signal::set_allocated_unit(std::string* unit) {
  if (unit != nullptr) {
    
  } else {
    
  }
  _impl_.unit_.SetAllocated(unit, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.unit_.IsDefault()) {
    _impl_.unit_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:canproto.Signal.unit)
}

// int64 raw_value = 4;
inline void Signal::clear_raw_value() {
  _impl_.raw_value_ = int64_t{0};
}
inline int64_t Signal::_internal_raw_value() const {
  return _impl_.raw_value_;
}
inline int64_t Signal::raw_value() const {
  // @@protoc_insertion_point(field_get:canproto.Signal.raw_value)
  return _internal_raw_value();
}
inline void Signal::_internal_set_raw_value(int64_t value) {
  
  _impl_.raw_value_ = value;
}
inline void Signal::set_raw_value(int64_t value) {
  _internal_set_raw_value(value);
  // @@protoc_insertion_point(field_set:canproto.Signal.raw_value)
}

// -------------------------------------------------------------------

// CanFrame

// uint32 message_id = 1;
inline void CanFrame::clear_message_id() {
  _impl_.message_id_ = 0u;
}
inline uint32_t CanFrame::_internal_message_id() const {
  return _impl_.message_id_;
}
inline uint32_t CanFrame::message_id() const {
  // @@protoc_insertion_point(field_get:canproto.CanFrame.message_id)
  return _internal_message_id();
}
inline void CanFrame::_internal_set_message_id(uint32_t value) {
  
  _impl_.message_id_ = value;
}
inline void CanFrame::set_message_id(uint32_t value) {
  _internal_set_message_id(value);
  // @@protoc_insertion_point(field_set:canproto.CanFrame.message_id)
}

// string message_name = 2;
inline void CanFrame::clear_message_name() {
  _impl_.message_name_.ClearToEmpty();
}
inline const std::string& CanFrame::message_name() const {
  // @@protoc_insertion_point(field_get:canproto.CanFrame.message_name)
  return _internal_message_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CanFrame::set_message_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:canproto.CanFrame.message_name)
}
inline std::string* CanFrame::mutable_message_name() {
  std::string* _s = _internal_mutable_message_name();
  // @@protoc_insertion_point(field_mutable:canproto.CanFrame.message_name)
  return _s;
}
inline const std::string& CanFrame::_internal_message_name() const {
  return _impl_.message_name_.Get();
}
inline void CanFrame::_internal_set_message_name(const std::string& value) {
  
  _impl_.message_name_.Set(value, GetArenaForAllocation());
}
inline std::string* CanFrame::_internal_mutable_message_name() {
  
  return _impl_.message_name_.Mutable(GetArenaForAllocation());
}
inline std::string* CanFrame::release_message_name() {
  // @@protoc_insertion_point(field_release:canproto.CanFrame.message_name)
  return _impl_.message_name_.Release();
}
inline void CanFrame::set_allocated_message_name(std::string* message_name) {
  if (message_name != nullptr) {
    
  } else {
    
  }
  _impl_.message_name_.SetAllocated(message_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_name_.IsDefault()) {
    _impl_.message_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:canproto.CanFrame.message_name)
}

// repeated .canproto.Signal signal_list = 3;
inline int CanFrame::_internal_signal_list_size() const {
  return _impl_.signal_list_.size();
}
inline int CanFrame::signal_list_size() const {
  return _internal_signal_list_size();
}
inline void CanFrame::clear_signal_list() {
  _impl_.signal_list_.Clear();
}
inline ::canproto::Signal* CanFrame::mutable_signal_list(int index) {
  // @@protoc_insertion_point(field_mutable:canproto.CanFrame.signal_list)
  return _impl_.signal_list_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::canproto::Signal >*
CanFrame::mutable_signal_list() {
  // @@protoc_insertion_point(field_mutable_list:canproto.CanFrame.signal_list)
  return &_impl_.signal_list_;
}
inline const ::canproto::Signal& CanFrame::_internal_signal_list(int index) const {
  return _impl_.signal_list_.Get(index);
}
inline const ::canproto::Signal& CanFrame::signal_list(int index) const {
  // @@protoc_insertion_point(field_get:canproto.CanFrame.signal_list)
  return _internal_signal_list(index);
}
inline ::canproto::Signal* CanFrame::_internal_add_signal_list() {
  return _impl_.signal_list_.Add();
}
inline ::canproto::Signal* CanFrame::add_signal_list() {
  ::canproto::Signal* _add = _internal_add_signal_list();
  // @@protoc_insertion_point(field_add:canproto.CanFrame.signal_list)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::canproto::Signal >&
CanFrame::signal_list() const {
  // @@protoc_insertion_point(field_list:canproto.CanFrame.signal_list)
  return _impl_.signal_list_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace canproto

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_can_5fmessage_2eproto
